# Generated by Django 3.2.7 on 2021-10-02 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211002_1926'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ganre',
            new_name='Genre',
        ),
    ]
