# Generated by Django 3.2.7 on 2022-02-09 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_news_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavoriteNews',
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
